version: '3'
services:

  mysql:
    image: mysql:5.7
    container_name: some-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw「
      
    volumes:
      - dbvolume/data:/var/lib/mysql          # ← 問題の箇所

volumes:                                      # ← Volumesでデータ領域をコンテナとして定義
  dbvolume: